### ISSUE TITLE
Missing fingerprint in honeybadger.notify

### ISSUE THREAD

**Issue by nadnerb** [honeybadger-io/honeybadger-python#115]
The python library seems to be missing a `fingerprint` which is available in the ruby gem and API. This makes using notify not as flexible when reporting errors using `honeybadger.notify`.

**Comment by joshuap** [comment]
@subzero10, @Kelvin4664 can probably help with this one if you can provide some direction.

**Comment by subzero10** [comment]
@nadnerb This should be fixed with `v0.10.0`!

**Comment by nadnerb** [comment]
Sorry for the late reply. Thank you! I will try it asap.

**Comment by subzero10** [comment]
@nadnerb I just released `v0.11.0` making `fingerprint` a top-level function parameter.
Note: it's a breaking change from `v0.10.0`

**Comment by nadnerb** [comment]
Hey @subzero10. Thanks for all the work and sorry for the slow response, I haven't been 100%. I noticed you put `fingerprint` at the method level in the `error_payload` method. However it has not been added to the `notify` method?

Thanks again.

**Comment by nadnerb** [comment]
@subzero10, @joshuap, would you like me to raise another bug for the notify issue?

**Comment by subzero10** [comment]
@nadnerb No need, I will get to it today!

**Comment by subzero10** [comment]
@nadnerb [PR](https://github.com/honeybadger-io/honeybadger-python/pull/119) ready!
cc @joshuap

**Comment by subzero10** [comment]
@nadnerb `v0.12.0` is released with the `fingerprint` in the `notify` method!

**Comment by nadnerb** [comment]
Fantastic, thank you!
