### ISSUE TITLE
Is there a way to verify that requests are sent successfully?

### ISSUE THREAD

**Issue by Marware** [honeybadger-io/honeybadger-python#137]
A way to check configuration is set correctly, for example I'm trying to get a response in case of wrong API key or failing to call honeybadger server

Thanks

**Comment by subzero10** [comment]
Hey @Marware,

If the API KEY is not set, is wrong, or the report request fails, an error will be reported to your logger instance, as seen [here](https://github.com/honeybadger-io/honeybadger-python/blob/master/honeybadger/connection.py#L17) and [here](https://github.com/honeybadger-io/honeybadger-python/blob/master/honeybadger/connection.py#L29). You can read more on how to setup logging [here](https://github.com/honeybadger-io/honeybadger-python#logging).

Let me know if this helps!
