### ISSUE TITLE
Allow non error events reporting

### ISSUE THREAD

**Issue by Kelvin4664** [honeybadger-io/honeybadger-python#169]
We'd like to send some non error events to the Honeybadger events api (https://docs.honeybadger.io/api/reporting-events/),
There's no out of the box way to do this in python in a non blocking way (like honeybadger.notify())

Can we have a new method, say `honeybadger.send_events()` for this purpose?

**Comment by stympy** [comment]
We definitely would like to add async sending of events to the events API. The method should be `honeybadger.event()` and it ideally should have a signature like the JS and Ruby libraries that accepts either a dictionary or a string and a dictionary as its arguments (see the [JS docs](https://docs.honeybadger.io/lib/javascript/guides/sending-events-to-insights/#manually-sending-events) for info on that). The method should add a `ts` field with the current timestamp to the JSON payload if the caller didn't include a `ts` in the dictionary.
