### ISSUE TITLE
Django get_object_or_404() is triggering Honeybadger

### ISSUE THREAD

**Issue by dotysan** [honeybadger-io/honeybadger-python#175]
Shouldn't that be a normal 404 instead of generating a honeybadger backtrace?

**Comment by subzero10** [comment]
Hey @dotysan, have you tried adding `Http404` to the `excluded_exceptions` config option?
it supports a list of errors to exclude from reporting to Honeybadger.

On another note, the default value of this option is an empty list - I think we should have some errors here by default (such as `Http404`).

**Comment by subzero10** [comment]
I'm closing the ticket but feel free to re-open if you have tried `excluded_exceptions` and did not work. If we decide to go for default ignored errors/exceptions, I'll create a separate issue to track that.

**Comment by dotysan** [comment]
Yes, I must be doing something wrong. Could you please re-open?

```Python
from django.http import Http404
HONEYBADGER = {
    'EXCLUDED_EXCEPTIONS': [Http404]
}
```

But no luck. What am I missing?

**Comment by subzero10** [comment]
> Yes, I must be doing something wrong. Could you please re-open?
> 
> ```python
> from django.http import Http404
> HONEYBADGER = {
>     'EXCLUDED_EXCEPTIONS': [Http404]
> }
> ```
> 
> But no luck. What am I missing?

Can you try just with a string? Like:
```python
HONEYBADGER = {
    'EXCLUDED_EXCEPTIONS': ['Http404']
}
```

This is how it's done in the [example configuration](https://github.com/honeybadger-io/honeybadger-python?tab=readme-ov-file#configuration) and by looking at the [code](https://github.com/honeybadger-io/honeybadger-python/blob/da1f8d60998379d5341b111982a50fd0ec2a5e4f/honeybadger/core.py#L51) I think it should be a string instead of the class name.

**Comment by dotysan** [comment]
> Can you try just with a string? Like:
> 
> ```python
> HONEYBADGER = {
>     'EXCLUDED_EXCEPTIONS': ['Http404']
> }
> ```

Aha! I was totally over-thinking that. Thx for the clue.
