### ISSUE TITLE
Local thread loses context in Flask app

### ISSUE THREAD

**Issue by LanceOlsen** [honeybadger-io/honeybadger-python#20]
I am running a Flask app, and using `notify` in an `errorhandler` decorator:

    @app.errorhandler(Exception)
    def handle_error(e):
        honeybadger.notify(e, context={})
        # other error related functionality

In the `__init__.py` file for this app I have:

    from honeybadger import honeybadger
    honeybadger.configure(api_key="blablah")

I'm getting the following error:

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/root/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/root/miniconda3/lib/python3.6/site-packages/flask/app.py", line 1518, in handle_user_exception
        return handler(e)
      File "/root/my_app/api.py", line 116, in handle_error
        honeybadger.notify(e, context={})
      File "/root/miniconda3/lib/python3.6/site-packages/honeybadger/core.py", line 43, in notify
        merged_context = self.thread_local.context
    AttributeError: '_thread._local' object has no attribute 'context'

**Comment by joshuap** [comment]
Thanks for the report @LanceOlsen. We'll work on getting this fixed.

**Comment by demsullivan** [comment]
Hey @LanceOlsen, I'm looking into this. I'm not able to reproduce it on my end, so I'd like to get some more information from you to see if we can track this down. Can you please provide the answers to the following:

- How are you importing honeybadger into `api.py`?
- How are your files structured? Which `__init__.py` has the `honeybadger.configure` line? Is it `/root/my_app/__init__.py` ?
- What command are you using to run your app? Are you running `api.py` directly, or some other script that then imports `api.py`?

Thanks!

**Comment by joshuap** [comment]
Closing this out due to lack of response. Feel free to reopen if you're still having this issue!

**Comment by ifoukarakis** [comment]
I also encountered the same problem. The problem is that if you try to call `honeybadger.notify` from a different thread than the one the global honeybadger object was created, the thread local variables disappear. Here's a script to reproduce it:
```
import threading
from honeybadger import honeybadger

def notifier():
    try:
        raise ValueError('Failure')
    except ValueError as e:
        honeybadger.notify(e)

honeybadger.configure(api_key='test')

notify_thread = threading.Thread(target=notifier)
notify_thread.start()
```

**Comment by demsullivan** [comment]
@ifoukarakis thanks for the sample! I'll look into getting this fixed up as soon as I can.
