### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by kereyroper** [honeybadger-io/honeybadger-python#21]
Django modified the middleware hooks for Django 1.10:
https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware

I have a fork with this working, but removed Flask support to make imports cleaner.
https://github.com/kereyroper/honeybadger-python/tree/django-1.10

**Comment by joshuap** [comment]
Thanks @kereyroper, we'll take a look at this.
