### ISSUE TITLE
Mutable default kwargs

### ISSUE THREAD

**Issue by dstuebe** [honeybadger-io/honeybadger-python#40]
I started to open a PR to replace `context={}` with `context=None` in `def notify(...`
https://github.com/honeybadger-io/honeybadger-python/blob/master/honeybadger/core.py#L42

It is not a bug perse, but I do expect to be able to pass None for an argument like that which currently causes an exception when reporting an exception!

Would folks be interested in changing the api to `def notify(self, exception=None, error_class=None, error_message=None, context=None):`

or even just adding a `if context:` before the `merged_context.update(context)` call?

Since `context` is not modified in the notify method (or any of the other methods that have a mutable default kwarg for context) it is not a bug perse, but it is certainly an API choice that surprised me.

**Comment by joshuap** [comment]
@demsullivan thoughts on this?

**Comment by demsullivan** [comment]
I don't see a problem with this - @dstuebe if you've got a PR to add that, go ahead and submit :) otherwise I'll get it patched up shortly.

**Comment by dstuebe** [comment]
@demsullivan which approach are you thinking of? Actually changing the interface to remove the mutable argument throughout the API or just adding some discrete `if arg is None` checks?

**Comment by demsullivan** [comment]
I think changing the default value in the method signature to `context=None` is fine - prior to `merged_context.update(context)` though we should confirm that `context is not None` and also that `context` is a dict.

**Comment by dstuebe** [comment]
Looks like three places to fix:
```
$ grep -r 'def ' honeybadger | grep '{}'
honeybadger/core.py:    def _send_notice(self, exception, exc_traceback=None, context={}):
honeybadger/core.py:    def notify(self, exception=None, error_class=None, error_message=None, context={}):
honeybadger/payload.py:def create_payload(exception, exc_traceback=None, config=None, context={}):
```
I blew away my first attempt at a PR when I realized it was more than one method.
