### ISSUE TITLE
Improve Lambda support

### ISSUE THREAD

**Issue by stympy** [honeybadger-io/honeybadger-python#60]
Errors can be lost when running in AWS Lambda because they are reported by a separate thread, and that thread can be terminated before the report is sent when Lambda ends execution of the function. When running in Lambda, the client should report errors immediately in the main thread rather than queueing them to be reported. For implementation ideas, see the `sync` option in our [Ruby library](https://github.com/honeybadger-io/honeybadger-ruby) and [this PR](https://github.com/honeybadger-io/honeybadger-ruby/pull/331) to see how we default to synchronous behavior (and add some additional Lambda-specific info) when running in the Lambda environment.

**Comment by tom-dq** [comment]
I'd be interested in testing this when it's ready! I'm using Honeybadger in this environment:
 - Python 3.7
 - AWS Lambda
 - Flask 1.1.2

For the time being, my inelegant, lumbering workaround is to hold up the response until all the "background threads" have finished up, where "background threads" makes some attempt to exclude the debugging instrumentation that VSCode has in the mix. In the off chance someone else finds it useful, here it is:

```python 
@app.teardown_request
def wait_for_background_threads(response):
    """Hold up the request until the background threads terminate."""
    JOIN_WAIT_SECONDS = 2.0

    main_thread = threading.main_thread()
    def should_join_on(thread):
        """Filter out all the flotsam and jetsam we don't need to wait on"""
        if thread == main_thread:
            return False

        is_pydev = getattr(thread, "is_pydev_daemon_thread", False) or getattr(thread, "pydev_do_not_trace", False)
        if is_pydev:
            return False

        return True

    joinable_threads = [thread for thread in threading.enumerate() if should_join_on(thread)]

    for thread in joinable_threads:
        t1 = time.time()
        join_success = False
        try:
            thread.join(JOIN_WAIT_SECONDS)
            join_success = True

        except RuntimeError as e:
            logging.warning(f"Got RuntimeError trying to .join() {thread}: {e}")

        t_wait = time.time() - t1

        if join_success:
            if thread.is_alive():
                logging.warning(f"Waited {JOIN_WAIT_SECONDS} for {thread} to .join() but it's still going.")

            else:
                logging.info(f"Waited {t_wait} for {thread} to finish up.")
```

**Comment by joshuap** [comment]
@tom-dq we have this fixed on the main branch if you're still interested in testing. You can see how to initialize the plugin [here](https://github.com/honeybadger-io/honeybadger-python/blob/master/examples/aws_lambda/handler.py).

We may be tweaking a few things before releasing (you can track the remaining work [here](https://github.com/honeybadger-io/honeybadger-python/milestone/1)).
