### ISSUE TITLE
Celery Integration

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-python#61]
A customer wasn't sure how to integrate Honeybadger with Django and Celery:

https://docs.celeryproject.org/en/stable/django/

These items are open to anyone who knows how to take this on:

- [ ] Reply with a code sample (or sample app/repo) of how to do it manually
- [ ] Add an official integration, if possible
- [ ] Otherwise, add the manual integration instructions to the Honeybadger docs

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_6p6g1)

**Comment by Kelvin4664** [comment]
So i tried this out and noticed the problem is very similar to that of AWS lambda. i.e honeybadger unable to override  `sys.excepthook` directly. The solution will take similar approach too
Fixing this next..

**Comment by joshuap** [comment]
@Kelvin4664 can you close out any issues that are completed in [this milestone](https://github.com/honeybadger-io/honeybadger-python/milestone/1) first? If there are any issue remaining, I'd like to get those finished up so that I can cut a new release with the new AWS Lambda integration.

**Comment by Kelvin4664** [comment]
Oh.. sure!
They're all done that's why i picked up this one.
Will close them now.

**Comment by stefanondisponibile** [comment]
A way to do this could be using [Celery's signals](https://docs.celeryproject.org/en/stable/userguide/signals.html#task-failure).

**Comment by Kelvin4664** [comment]
> Celery's signals

Good point @stefanondisponibile
But i fear failure may be critical to the point where failure signals are not sent. What do you think?

**Comment by stefanondisponibile** [comment]
yeah, good point too @Kelvin4664, I think what you're suggesting may happen.
What you think of [this](https://github.com/getsentry/sentry-python/blob/4c09f3203d6d19789c6fa729a2e46557ad4ea913/sentry_sdk/integrations/celery.py) approach instead?
