### ISSUE TITLE
Use in AWS Glue

### ISSUE THREAD

**Issue by kstevens715** [honeybadger-io/honeybadger-python#62]
I'm trying to use `honeybadger-python` in an AWS Glue job. I'm able to install this module, along with `psutil` and `six` by specifying them in the "Python library path" option and providing them as either zip or whl archives.

Unfortunately, when I try running the job I get the error below. I don't think AWS Glue is compatible with modules that rely on C-extensions:

```
ImportError: cannot import name '_psutil_linux' from 'psutil' (/tmp/psutil-5.8.0-cp37-cp37m-manylinux2010_x86_64.whl/psutil/__init__.py)
```

To work-around the problem, I hacked the `honeybadger-python` source code to remove the dependency on `psutil` which wasn't important to me at this time.

Is there any interest in making `psutil` optional? Python 3 has ways of detecting if a module is available. If the module isn't available, it could skip [the stats part of the payload](https://github.com/honeybadger-io/honeybadger-python/blob/db28b0c5326efc95d7e1760cefc86d48545faf52/honeybadger/payload.py#L77-L85). If there's interest, I might try making a pull request.

**Comment by joshuap** [comment]
@kstevens715 I'd be OK with that solution if stats are still "on by default" on most platforms. I.e., I'd rather not have to do this for stats to be enabled: `pip install honeybadger && pip install psutil`. Is that possible?

cc @demsullivan

**Comment by kstevens715** [comment]
@joshuap Yes, for use in Glue I would explicitly install `honeybadger` without the dependency. But the defaults would remain the same.
