### ISSUE TITLE
Document AWS Lambda setup in README

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-python#70]
Pending #69

Add a section to the README on how to set up Honeybadger in an AWS Lambda function, like we do for Django and Flask:

https://github.com/honeybadger-io/honeybadger-python#django

**Comment by Kelvin4664** [comment]
Since we no longer register the lambda plugin explicitly, I believe it can fall under [https://github.com/honeybadger-io/honeybadger-python#other-frameworks--plain-python-app](url)
There is no additional step involved. Any thoughts?

**Comment by joshuap** [comment]
@Kelvin4664 I think I’d prefer to have a section right above other frameworks/plain python, but maybe it could just give a simple example of a Lambda function and say that the plugin is automatically configured?

**Comment by Kelvin4664** [comment]
Right.. @joshuap A simple example function would suffice. At least to be explicit that we support lambda functions.
