### ISSUE TITLE
Move AWS Lambda trace_id from context to details payload?

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-python#71]
When I tested the new lambda plugin, it seemed a bit random that the trace id was in the `context` section, but everything else was in `Lambda Details`. Is there a reason we did it that way in the [Ruby plugin](https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/plugins/lambda.rb#L20)? cc @stympy @rabidpraxis 

https://github.com/honeybadger-io/honeybadger-python/pull/67/files#diff-8482ef1a1b7b34b6ab5e701bf2a3c225949fcbb01669c9cf8a4fa7c962a63b8aR134

**Comment by rabidpraxis** [comment]
I believe we put trace_id in the context so it would be searchable.

**Comment by joshuap** [comment]
Ah, that's what I was missing. I forgot that details are not searchable.
