### ISSUE TITLE
Add a log handler

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-python#82]
I would like to add a log handler that users can configure in their applications to automatically report error logs to Honeybadger.

Example:

```python
except IndexError:
    logger.exception("Something bad happened")
```

```python
logging.config.dictConfig({
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'honeybadger': {
            'level': 'ERROR',
            'class': 'honeybadger.contrib.logger.HoneybadgerHandler',
        },
    },
    'loggers': {
        # root logger
        '': {
            'level': 'WARNING',
            'handlers': ['console', 'honeybadger'],
        },
    },
})
```

For more in-depth examples of how this will be used, see:

https://lincolnloop.com/blog/disabling-error-emails-django/
https://lincolnloop.com/blog/django-logging-right-way/
https://www.youtube.com/watch?v=ziegOuE7M4A&t=1s

**Comment by Kelvin4664** [comment]
Hey @joshuap 
Are we limiting this to just exceptions? or info and warnings as well

**Comment by joshuap** [comment]
@Kelvin4664 sorry just got back from vacation. I think the idea is that we would report all logs that are >= to the configured `level` for our handler—so yeah, I imagine it could include info if the level were `'INFO'` (but for most people it will be `'ERROR'`).
